from typing import Protocol, runtime_checkable, Any


@runtime_checkable
class AsyncStorageNode(Protocol):
    """Protocol for async storage nodes."""

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def get(self, key: str) -> Any: ...
    async def set(self, key: str, value: Any, ttl: float | None = None) -> bool: ...
    async def delete(self, key: str) -> bool: ...


@runtime_checkable
class StorageNode(Protocol):
    """Protocol for synchronous storage nodes."""

    def start(self) -> None: ...
    def stop(self) -> None: ...
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any, ttl: float | None = None) -> bool: ...
    def delete(self, key: str) -> bool: ...
