from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class AsyncStorageNode(Protocol):
    """Protocol for async storage nodes."""

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def get(self, key: str) -> Any: ...
    async def set(self, key: str, value: Any, ttl: float | None = None) -> bool: ...
    async def delete(self, key: str) -> bool: ...


@runtime_checkable
class StorageNode(Protocol):
    """Protocol for synchronous storage nodes."""

    def start(self) -> None: ...
    def stop(self) -> None: ...
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any, ttl: float | None = None) -> bool: ...
    def delete(self, key: str) -> bool: ...


@runtime_checkable
class AsyncReplicaHandle(Protocol):
    """ReplicaHandle makes a common interface for local or remote replicas, so the node can treat them uniformly."""

    async def get_versioned(self, key: str) -> tuple[Any, int, bool] | None: ...
    async def set(self, key: str, value: Any, ttl: float | None, ts: int) -> bool: ...
    async def delete(self, key: str, ts: int) -> bool: ...


@runtime_checkable
class ReplicaHandle(Protocol):
    """ReplicaHandle makes a common interface for local or remote replicas, so the node can treat them uniformly."""

    def get_versioned(self, key: str) -> tuple[Any, int, bool] | None: ...
    def set(self, key: str, value: Any, ttl: float | None, ts: int) -> bool: ...
    def delete(self, key: str, ts: int) -> bool: ...
