from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Store(Protocol):
    def get(self, key: str) -> Any | None: ...
    def set(
        self, key: str, value: Any, ttl: float | None = None, **kwargs: Any
    ) -> bool: ...
    def delete(self, key: str, **kwargs: Any) -> bool: ...
    def keys(self) -> list[str]: ...
    def scan(self, pattern: str) -> list[tuple[str, Any]]: ...
    def scan_keys(self, pattern: str) -> list[str]: ...
    def flush_all(self) -> None: ...
    def flush_keys(self, pattern: str) -> int: ...
    def clear(self) -> None: ...
    def purge_expired(self) -> int: ...
    def __len__(self) -> int: ...


@runtime_checkable
class VersionedStore(Store, Protocol):
    def get_versioned(self, key: str) -> tuple[Any, int, bool] | None: ...
