from typing import Protocol, runtime_checkable
from dlstorage.types import NodeInfo


@runtime_checkable
class Ring(Protocol):
    def add(self, node: NodeInfo) -> None: ...
    def remove(self, node: NodeInfo) -> None: ...
    def get_node(self, key: str) -> NodeInfo | None: ...
    def get_nodes(self, key: str, n: int = 1) -> list[NodeInfo]: ...
    def nodes(self) -> list[NodeInfo]: ...
    def __len__(self) -> int: ...
